// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4mod1_GP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod1_timepoint_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod2_GP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod2_GP_sens100_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod2_timepoint_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod3_GP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod3_timepoint_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod4_GP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod4_timepoint_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod_GP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod_GP_overdisp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod_timepoint_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mod_timepoint_overdisp_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4mod1_GP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod1_GP_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod1_timepoint_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod1_timepoint_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod2_GP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod2_GP_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod2_GP_sens100_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod2_GP_sens100_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod2_timepoint_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod2_timepoint_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod3_GP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod3_GP_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod3_timepoint_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod3_timepoint_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod4_GP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod4_GP_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod4_timepoint_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod4_timepoint_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod_GP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod_GP_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod_GP_overdisp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod_GP_overdisp_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod_timepoint_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod_timepoint_mod, 0},
    {"_rcpp_module_boot_stan_fit4mod_timepoint_overdisp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mod_timepoint_overdisp_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_epipool(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
